---
title: "Research"
toc: false
bibliography: ./assets/bib/publications_html.bib
engine: knitr
execute: 
  echo: false
---

```{css}
cite {
  color: #515151;
  font-style: normal;
}

p {
  line-height: 1.25;
  padding-left: 30px;
  text-indent: -30px;
}

.relax {
  line-height: 1.5;
  padding-left: 0px;
  text-indent: 0px;
}

```

<!-- 
Updating the bib:
    - must update by hand the file publications_html.bib in mybib repo
    - once updated, below code downloads current version and loads into R
    - must reference relevant article in relevant pane (publications or presentations)
Afterwards, update the following:
    - Your CV
    - Research Gate
    - Google scholar
-->

```{r}
#| label: bib-setup
#| eval: true
#| message: false

library("RefManageR")
library("here")
library("dplyr")
library("tidyr")

# Url to github repo
# fileUrl <- "https://raw.githubusercontent.com/jvcasillas/mybib/master/publications_html.bib"

# Download .bib file
# download.file(
#   url = fileUrl, 
#   destfile = here("assets", "bib", "publications_html.bib"), 
#   method = "curl"
#   )

# Load bib
bib <- ReadBib(here("assets", "bib", "publications_html.bib"), check = FALSE)

# Create csv of citekeys
cite_key_list <- bind_cols(
  bib$key %>% unlist %>% tibble::enframe(name = NULL), 
  bib$bibtype %>% unlist %>% tibble::enframe(name = NULL), 
  bib$year %>% unlist %>% tibble::enframe(name = NULL)
  ) %>% 
  rename(citekey = value...1, type = value...2, year = value...3) |> 
  tidyr::separate(
    col = citekey, 
    into = c("authors", "title", "type_check", "year_check"), 
    sep = "_", 
    remove = F
  )

# Set bib options
BibOptions(
  bib.style = "authoryear", 
  style = "markdown", 
  dashed = FALSE, 
  sorting = "ynt", 
  max.names = 10, 
  first.inits = TRUE, 
  check.entries = FALSE
  )

# Printer function for refs
ref_printer <- function(pubs) {
  for (i in pubs) {
    print(bib[key = i]); cat("\n")
  }
}
```


<!-- ::: panel-tabset -->

### Monographs

```{r}
#| label: print-books
#| results: 'asis'
cite_key_list |>
  filter(
    type_check == "book",
    !(year %in% c("In press", "Under review", "in preparation"))
    ) |> 
  arrange(desc(year)) |>
  pull(citekey) |> 
  ref_printer()
```

### Journal articles 

#### In preparation

```{r}
#| label: print-in-prep
#| results: 'asis'
cite_key_list |>
  filter(type_check == "journalarticle",
         year_check == "preparation") |>
  arrange(desc(year)) |>
  pull(citekey) |> 
  ref_printer()
```

#### Under review/revision

```{r}
#| label: print-submitted
#| results: 'asis'
cite_key_list |>
  filter(type_check == "journalarticle",
         year_check == "review") |>
  arrange(desc(year)) |>
  pull(citekey) |> 
  ref_printer()
```

#### In press

```{r}
#| label: print-in-press
#| results: 'asis'
cite_key_list |>
  filter(type_check == "journalarticle",
         year_check == "press") |> 
  arrange(desc(year)) |>
  pull(citekey) |> 
  ref_printer()
```

#### Published

```{r}
#| label: print-recent-pubs
#| results: 'asis'
cite_key_list |>
  filter(
    type_check == "journalarticle", 
    !(year_check %in% c("press", "review", "preparation"))
    ) |> 
  arrange(desc(year)) |>
  pull(citekey) |> 
  ref_printer()
```


<!-- :::  -->
